package com.stavro_xhardha.core_module.brain

//App constants
const val APPLICATION_TAG = "PocketTreasure"
const val SHARED_PREFERENCES_TAG = "pocket_treasure_app"
const val PRAYER_API_BASE_URL: String = "https://api.aladhan.com/v1/"
const val INITIAL_PAGE_SIZE = 20
const val UNSPLASH_BASE_URL = "https://api.unsplash.com/search/photos"
const val UNPLASH_QUERY_VALUE = "islam|mosque"
const val CLIENT_ID = "9c80ea2aa631bda7ec75798cd6f0cfc2008ea6152721d80913464c4fc2f142bc"
const val CLIENT_SECRET = "a69a283d85e85b8a72309e50c219211ab13284c4e0190ae30199e8e1d0ac3aa3"
const val REQUEST_STORAGE_PERMISSION = 355
const val REQUEST_LOCATION_PERMISSION = 366
const val REQUEST_CHECK_LOCATION_SETTINGS = 367
const val QURAN_API_CALL_BASE_URL = "https://api.alquran.cloud/v1/quran/ar.alafasy"
const val FIRST_SURAH_SENTENCE = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ"
const val PLAY_STORE_URL =
    "https://play.google.com/store/apps/details?id=com.stavro_xhardha.pockettreasure"
const val COUNTRY_SHARED_PREFERENCE_KEY = "app_country"
const val CAPITAL_SHARED_PREFERENCES_KEY = "app_capital"
const val FAJR_KEY = "app_fejr"
const val SUNRISE_KEY = "app_sunrise"
const val DHUHR_KEY = "app_dhuhr"
const val ASR_KEY = "app_asr"
const val MAGHRIB_KEY = "app_maghrib"
const val ISHA_KEY = "app_isha"
const val MIDNIGHT_KEY = "app_midnight"
const val HIRJI_DAY_OF_MONTH_KEY = "app_hijri_day_of_month"
const val HIJRI_MONTH_NAME_KEY = "app_hijri_month_name"
const val HIJRI_YEAR_KEY = "app_hijri_year"
const val GREGORIAN_DAY_KEY = "app_gregorian_day"
const val GREGORIAN_MONTH_KEY = "app_gregorian_month"
const val GREGORIAN_MONTH_NAME_KEY = "app_gregorian_month_name"
const val GREGORIAN_YEAR_KEY = "app_gregorian_year"
const val NOTIFY_USER_FOR_FAJR = "app_notify_fajr"
const val NOTIFY_USER_FOR_DHUHR = "app_notify_dhuhr"
const val NOTIFY_USER_FOR_ASR = "app_notify_asr"
const val NOTIFY_USER_FOR_MAGHRIB = "app_notify_maghrib"
const val NOTIFY_USER_FOR_ISHA = "app_notify_isha"
const val COUNTRY_UPDATED = "app_country_updated"
const val LATITUDE_KEY = "app_latitude_key"
const val LONGITUDE_KEY = "app_longitude_key"
const val PENDING_INTENT_FIRE_NOTIFICATION_FAJR = 2002
const val PENDING_INTENT_FIRE_NOTIFICATION_DHUHR = 2003
const val PENDING_INTENT_FIRE_NOTIFICATION_ASR = 2004
const val PENDING_INTENT_FIRE_NOTIFICATION_MAGHRIB = 2005
const val PENDING_INTENT_FIRE_NOTIFICATION_ISHA = 2006
const val PENDING_INTENT_FIRE_MAIN_ACTIVITY = 2007
const val MAKKAH_LATITUDE = 21.4225
const val MAKKAH_LONGITUDE = 39.8262
const val PRAYER_TITLE = "prayer_title"
const val PRAYER_DESCRIPTION = "prayer_description"
const val FAJR = "Fajr Time"
const val DHUHR = "Dhuhr Time"
const val ASR = "Asr Time"
const val MAGHRIB = "Maghrib Time"
const val ISHA = "Isha Time"
const val FULL_IMAGE_SAVED_STATE = "bundle_image"
const val NAMES_LIST_STATE = "bundle_names"
const val HOME_DATA_LIST = "bundle_home_prayers"
const val NIGHT_MODE_KEY = "bundle_app_theme"